export interface Quote {
  id: number;
  text: string;
  source: string;
  reference: string;
  category: 'motivation' | 'prayer' | 'guidance' | 'remembrance' | 'ramadan' | 'names_of_allah';
  arabic?: string;
}

// Helper function to transform your quote format
const transformQuote = (rawQuote: any): Quote => {
  const referenceMatch = rawQuote.reference.match(/^(Qur'an|Hadith.*?|Names of Allah)\s*[-:]?\s*(.*)$/);
  
  let source = 'Unknown';
  let reference = '';
  
  if (referenceMatch) {
    source = referenceMatch[1].trim();
    reference = referenceMatch[2].trim();
  } else {
    source = rawQuote.reference;
  }
  
  return {
    id: rawQuote.id,
    text: rawQuote.text,
    source: source,
    reference: reference,
    category: rawQuote.category,
    arabic: rawQuote.arabic
  };
};


const quotesDatabase = {
    motivation: [
      {
        id: 1,
        text: "Verily, with hardship comes ease.",
        reference: "Qur'an 94:6",
        arabic: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا",
        category: "motivation",
      },
      {
        id: 2,
        text: "Allah does not burden a soul beyond that it can bear.",
        reference: "Qur'an 2:286",
        arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
        category: "motivation",
      },
      {
        id: 3,
        text: "The best of people are those that bring most benefit to the rest of mankind.",
        reference: "Hadith - Daraqutni",
        arabic: "",
        category: "motivation",
      },
      {
        id: 4,
        text: "So be patient. Indeed, the promise of Allah is truth.",
        reference: "Qur'an 30:60",
        arabic: "فَاصْبِرْ إِنَّ وَعْدَ اللَّهِ حَقٌّ",
        category: "motivation",
      },
      {
        id: 5,
        text: "And He is with you wherever you are.",
        reference: "Qur'an 57:4",
        arabic: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ",
        category: "motivation",
      },
      {
        id: 6,
        text: "The strong person is not the one who can wrestle someone else down. The strong person is the one who can control himself when he is angry.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "motivation",
      },
      {
        id: 7,
        text: "Do not lose hope, nor be sad.",
        reference: "Qur'an 3:139",
        arabic: "وَلَا تَهِنُوا وَلَا تَحْزَنُوا",
        category: "motivation",
      },
      {
        id: 8,
        text: "Take one step towards Allah, He will take ten steps towards you. Walk towards Allah, He will run towards you.",
        reference: "Hadith Qudsi",
        arabic: "",
        category: "motivation",
      },
      {
        id: 9,
        text: "Perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. And Allah knows, while you know not.",
        reference: "Qur'an 2:216",
        arabic: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ",
        category: "motivation",
      },
      {
        id: 10,
        text: "Indeed, Allah is with those who are patient.",
        reference: "Qur'an 8:46",
        arabic: "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
        category: "motivation",
      },
      {
        id: 11,
        text: "Whoever is slow in doing good deeds, his lineage will not make him go faster.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "motivation",
      },
      {
        id: 12,
        text: "Allah does not look at your forms and possessions, but He looks at your hearts and your deeds.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "motivation",
      },
      {
        id: 13,
        text: "When Allah desires good for someone, He tries him with hardships.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "motivation",
      },
      {
        id: 14,
        text: "Do not be grieved; indeed Allah is with us.",
        reference: "Qur'an 9:40",
        arabic: "لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا",
        category: "motivation",
      },
      {
        id: 15,
        text: "The believer who mixes with people and bears their annoyance with patience will have a greater reward than the believer who does not mix with people.",
        reference: "Hadith - Ibn Majah",
        arabic: "",
        category: "motivation",
      },
    ],
    prayer: [
      {
        id: 16,
        text: "And your Lord says: Call upon Me; I will respond to you.",
        reference: "Qur'an 40:60",
        arabic: "وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ",
        category: "prayer",
      },
      {
        id: 17,
        text: "When My servants ask you concerning Me, I am indeed close to them.",
        reference: "Qur'an 2:186",
        arabic: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ",
        category: "prayer",
      },
      {
        id: 18,
        text: "The dua of a fasting person will not be refused.",
        reference: "Hadith - Ibn Majah",
        arabic: "",
        category: "prayer",
      },
      {
        id: 19,
        text: "Ask Allah for everything, even the lace of your shoes. If Allah does not provide, it will never be available.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "prayer",
      },
      {
        id: 20,
        text: "Dua is the weapon of the believer.",
        reference: "Hadith - Hakim",
        arabic: "",
        category: "prayer",
      },
      {
        id: 21,
        text: "The most beloved deed to Allah is the one that is continuous, even if it is small.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "prayer",
      },
      {
        id: 22,
        text: "And seek help through patience and prayer.",
        reference: "Qur'an 2:45",
        arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
        category: "prayer",
      },
      {
        id: 23,
        text: "Indeed, prayer prohibits immorality and wrongdoing.",
        reference: "Qur'an 29:45",
        arabic: "إِنَّ الصَّلَاةَ تَنْهَىٰ عَنِ الْفَحْشَاءِ وَالْمُنكَرِ",
        category: "prayer",
      },
      {
        id: 24,
        text: "The closest that a servant is to his Lord is when he is in prostration.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "prayer",
      },
      {
        id: 25,
        text: "There is nothing more noble in the sight of Allah than dua.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "prayer",
      },
      {
        id: 26,
        text: "Make dua even if you think it will not be answered, because dua itself is worship.",
        reference: "Hadith - Ahmad",
        arabic: "",
        category: "prayer",
      },
      {
        id: 27,
        text: "The supplication made between the adhan and iqama is never rejected.",
        reference: "Hadith - Abu Dawud",
        arabic: "",
        category: "prayer",
      },
      {
        id: 28,
        text: "Whoever prays Fajr in congregation is under Allah's protection.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "prayer",
      },
      {
        id: 29,
        text: "Allah descends to the lowest heaven during the last third of the night, asking: 'Who is calling upon Me that I may answer him?'",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "prayer",
      },
      {
        id: 30,
        text: "Prayer is the key to Paradise.",
        reference: "Hadith - Ahmad",
        arabic: "",
        category: "prayer",
      },
    ],
    guidance: [
      {
        id: 31,
        text: "Indeed, Allah will not change the condition of a people until they change what is in themselves.",
        reference: "Qur'an 13:11",
        arabic:
          "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ",
        category: "guidance",
      },
      {
        id: 32,
        text: "O you who have believed, seek help through patience and prayer.",
        reference: "Qur'an 2:153",
        arabic:
          "يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
        category: "guidance",
      },
      {
        id: 33,
        text: "The best richness is the richness of the soul.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "guidance",
      },
      {
        id: 34,
        text: "Whoever follows a path in pursuit of knowledge, Allah will make easy for him a path to Paradise.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "guidance",
      },
      {
        id: 35,
        text: "The most beloved of people to Allah are those who are most beneficial to people.",
        reference: "Hadith - Tabarani",
        arabic: "",
        category: "guidance",
      },
      {
        id: 36,
        text: "Speak good or remain silent.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "guidance",
      },
      {
        id: 37,
        text: "The believer does not slander, curse, or speak in an obscene or foul manner.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "guidance",
      },
      {
        id: 38,
        text: "None of you truly believes until he loves for his brother what he loves for himself.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "guidance",
      },
      {
        id: 39,
        text: "Tie your camel first, then put your trust in Allah.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "guidance",
      },
      {
        id: 40,
        text: "A good word is charity.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "guidance",
      },
      {
        id: 41,
        text: "Richness is not having many possessions, but richness is being content with oneself.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "guidance",
      },
      {
        id: 42,
        text: "The best of you are those who are best to their families.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "guidance",
      },
      {
        id: 43,
        text: "Whoever believes in Allah and the Last Day should speak good or remain silent.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "guidance",
      },
      {
        id: 44,
        text: "The strong believer is better and more beloved to Allah than the weak believer, while there is good in both.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "guidance",
      },
      {
        id: 45,
        text: "A man's feet will not move on the Day of Judgment until he is asked about his life and how he spent it.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "guidance",
      },
    ],
    remembrance: [
      {
        id: 46,
        text: "Remember Me, and I will remember you.",
        reference: "Qur'an 2:152",
        arabic: "فَاذْكُرُونِي أَذْكُرْكُمْ",
        category: "remembrance",
      },
      {
        id: 47,
        text: "Verily, in the remembrance of Allah do hearts find rest.",
        reference: "Qur'an 13:28",
        arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
        category: "remembrance",
      },
      {
        id: 48,
        text: "Whoever says SubhanAllah wa bihamdihi one hundred times a day will have his sins forgiven even if they are like the foam of the sea.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 49,
        text: "The best remembrance is La ilaha illa Allah.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 50,
        text: "Allah says: 'I am as My servant thinks I am, and I am with him when he remembers Me.'",
        reference: "Hadith Qudsi - Bukhari",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 51,
        text: "Two words are light on the tongue, weigh heavily in the balance, and are loved by the Most Merciful: SubhanAllah wa bihamdihi, SubhanAllahi al-Azeem.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 52,
        text: "Whoever says 'SubhanAllahi wa bihamdihi' 100 times in the morning and evening, no one will bring better than what he brought except someone who said the same or more.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 53,
        text: "The most beloved words to Allah are four: SubhanAllah, Alhamdulillah, La ilaha illa Allah, and Allahu Akbar.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 54,
        text: "Shall I not inform you of the best of your deeds, the purest in the sight of your Lord? It is the remembrance of Allah.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 55,
        text: "When a group of people sit together remembering Allah, the angels surround them, mercy covers them, peace descends upon them, and Allah mentions them to those near Him.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 56,
        text: "The example of the one who remembers his Lord and the one who does not is like the living and the dead.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 57,
        text: "Remember Allah during times of ease and He will remember you during times of difficulty.",
        reference: "Hadith - Ahmad",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 58,
        text: "There is a polish for everything that removes rust, and the polish for the heart is remembrance of Allah.",
        reference: "Hadith - Bayhaqi",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 59,
        text: "Whoever reads Ayatul Kursi after every obligatory prayer, nothing prevents him from entering Paradise except death.",
        reference: "Hadith - Nasa'i",
        arabic: "",
        category: "remembrance",
      },
      {
        id: 60,
        text: "The house in which Allah is remembered and the house in which Allah is not remembered are like the living and the dead.",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "remembrance",
      },
    ],
    ramadan: [
      {
        id: 61,
        text: "Ramadan is the month in which was revealed the Qur'an, a guidance for mankind.",
        reference: "Qur'an 2:185",
        arabic: "شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ",
        category: "ramadan",
      },
      {
        id: 62,
        text: "When Ramadan enters, the gates of Paradise are opened, the gates of Hellfire are closed and the devils are chained.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 63,
        text: "Whoever fasts during Ramadan with faith and seeking reward, his past sins will be forgiven.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 64,
        text: "Whoever stands in prayer during Laylatul Qadr with faith and seeking reward, his past sins will be forgiven.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 65,
        text: "Seek Laylatul Qadr in the last ten nights of Ramadan.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 66,
        text: "When the first night of Ramadan comes, the devils and rebellious jinn are chained.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 67,
        text: "Whoever provides iftar for a fasting person will have a reward like his, without any reduction in the fasting person's reward.",
        reference: "Hadith - Tirmidhi",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 68,
        text: "Fasting is a shield. When one of you is fasting, let him not utter obscenities or act in an ignorant manner.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 69,
        text: "Every action of the son of Adam is multiplied; a good deed is multiplied tenfold up to seven hundred times. Allah says: 'Except fasting, for it is for Me and I shall reward it.'",
        reference: "Hadith - Muslim",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 70,
        text: "The fasting person has two moments of joy: when he breaks his fast and when he meets his Lord.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 71,
        text: "Fasting and the Quran will intercede for the servant on the Day of Judgment.",
        reference: "Hadith - Ahmad",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 72,
        text: "Ramadan has come to you, a blessed month. Allah has made fasting during it obligatory upon you.",
        reference: "Hadith - Nasa'i",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 73,
        text: "The breath of a fasting person is sweeter to Allah than the fragrance of musk.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 74,
        text: "There is a gate in Paradise called Ar-Rayyan through which only those who fasted will enter.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
      {
        id: 75,
        text: "Umrah performed in Ramadan is equivalent to Hajj.",
        reference: "Hadith - Bukhari",
        arabic: "",
        category: "ramadan",
      },
    ],
    names_of_allah: [
      {
        id: 76,
        text: "O Allah, You are Ar-Rahman (The Most Merciful). Pour Your mercy upon us and forgive our shortcomings.",
        reference: "Names of Allah",
        arabic: "يَا رَحْمَٰنُ",
        category: "names_of_allah",
      },
      {
        id: 77,
        text: "O Allah, You are Ar-Raheem (The Most Compassionate). Bless us with Your endless compassion.",
        reference: "Names of Allah",
        arabic: "يَا رَحِيمُ",
        category: "names_of_allah",
      },
      {
        id: 78,
        text: "O Allah, You are Al-Malik (The King). Guide us to live righteously under Your sovereignty.",
        reference: "Names of Allah",
        arabic: "يَا مَلِكُ",
        category: "names_of_allah",
      },
      {
        id: 79,
        text: "O Allah, You are Al-Quddus (The Most Sacred). Purify our hearts and souls.",
        reference: "Names of Allah",
        arabic: "يَا قُدُّوسُ",
        category: "names_of_allah",
      },
      {
        id: 80,
        text: "O Allah, You are As-Salam (The Source of Peace). Grant us inner peace and tranquility.",
        reference: "Names of Allah",
        arabic: "يَا سَلَامُ",
        category: "names_of_allah",
      },
      {
        id: 81,
        text: "O Allah, You are Al-Mu'min (The Granter of Security). Protect us from all fears and grant us safety.",
        reference: "Names of Allah",
        arabic: "يَا مُؤْمِنُ",
        category: "names_of_allah",
      },
      {
        id: 82,
        text: "O Allah, You are Al-Muhaymin (The Guardian). Watch over us and keep us safe from harm.",
        reference: "Names of Allah",
        arabic: "يَا مُهَيْمِنُ",
        category: "names_of_allah",
      },
      {
        id: 83,
        text: "O Allah, You are Al-Aziz (The Almighty). Grant us strength in our times of weakness.",
        reference: "Names of Allah",
        arabic: "يَا عَزِيزُ",
        category: "names_of_allah",
      },
      {
        id: 84,
        text: "O Allah, You are Al-Jabbar (The Compeller). Mend our broken hearts and restore what has been lost.",
        reference: "Names of Allah",
        arabic: "يَا جَبَّارُ",
        category: "names_of_allah",
      },
      {
        id: 85,
        text: "O Allah, You are Al-Mutakabbir (The Supreme). Remove arrogance from our hearts.",
        reference: "Names of Allah",
        arabic: "يَا مُتَكَبِّرُ",
        category: "names_of_allah",
      },
      {
        id: 86,
        text: "O Allah, You are Al-Khaliq (The Creator). Help us appreciate the beauty of Your creation.",
        reference: "Names of Allah",
        arabic: "يَا خَالِقُ",
        category: "names_of_allah",
      },
      {
        id: 87,
        text: "O Allah, You are Al-Bari (The Maker). Fashion our character to be pleasing to You.",
        reference: "Names of Allah",
        arabic: "يَا بَارِئُ",
        category: "names_of_allah",
      },
      {
        id: 88,
        text: "O Allah, You are Al-Musawwir (The Fashioner). Shape our lives according to Your wisdom.",
        reference: "Names of Allah",
        arabic: "يَا مُصَوِّرُ",
        category: "names_of_allah",
      },
      {
        id: 89,
        text: "O Allah, You are Al-Ghaffar (The Forgiving). Forgive our sins and accept our repentance.",
        reference: "Names of Allah",
        arabic: "يَا غَفَّارُ",
        category: "names_of_allah",
      },
      {
        id: 90,
        text: "O Allah, You are Al-Qahhar (The Subduer). Subdue our nafs and help us overcome our desires.",
        reference: "Names of Allah",
        arabic: "يَا قَهَّارُ",
        category: "names_of_allah",
      },
      {
        id: 91,
        text: "O Allah, You are Al-Wahhab (The Bestower). Grant us from Your limitless bounty.",
        reference: "Names of Allah",
        arabic: "يَا وَهَّابُ",
        category: "names_of_allah",
      },
      {
        id: 92,
        text: "O Allah, You are Ar-Razzaq (The Provider). Provide for us from sources we cannot imagine.",
        reference: "Names of Allah",
        arabic: "يَا رَزَّاقُ",
        category: "names_of_allah",
      },
      {
        id: 93,
        text: "O Allah, You are Al-Fattah (The Opener). Open for us doors of goodness and opportunity.",
        reference: "Names of Allah",
        arabic: "يَا فَتَّاحُ",
        category: "names_of_allah",
      },
      {
        id: 94,
        text: "O Allah, You are Al-Aleem (The All-Knowing). Guide us with Your perfect knowledge.",
        reference: "Names of Allah",
        arabic: "يَا عَلِيمُ",
        category: "names_of_allah",
      },
      {
        id: 95,
        text: "O Allah, You are Al-Qabid (The Withholder) and Al-Basit (The Extender). Grant us balance in all affairs.",
        reference: "Names of Allah",
        arabic: "يَا قَابِضُ يَا بَاسِطُ",
        category: "names_of_allah",
      },
      {
        id: 96,
        text: "O Allah, You are Al-Khafid (The Abaser) and Ar-Rafi (The Exalter). Raise our ranks in this life and the next.",
        reference: "Names of Allah",
        arabic: "يَا خَافِضُ يَا رَافِعُ",
        category: "names_of_allah",
      },
      {
        id: 97,
        text: "O Allah, You are Al-Mu'izz (The Honorer) and Al-Mudhill (The Humiliator). Honor us with Your obedience.",
        reference: "Names of Allah",
        arabic: "يَا مُعِزُّ يَا مُذِلُّ",
        category: "names_of_allah",
      },
      {
        id: 98,
        text: "O Allah, You are As-Sami (The All-Hearing). Hear our prayers and answer our calls.",
        reference: "Names of Allah",
        arabic: "يَا سَمِيعُ",
        category: "names_of_allah",
      },
      {
        id: 99,
        text: "O Allah, You are Al-Basir (The All-Seeing). Watch over us with Your loving gaze.",
        reference: "Names of Allah",
        arabic: "يَا بَصِيرُ",
        category: "names_of_allah",
      },
      {
        id: 100,
        text: "O Allah, You are Al-Hakam (The Judge). Judge between us and our enemies with truth.",
        reference: "Names of Allah",
        arabic: "يَا حَكَمُ",
        category: "names_of_allah",
      },
      {
        id: 101,
        text: "O Allah, You are Al-Adl (The Just). Help us to always act with justice and fairness.",
        reference: "Names of Allah",
        arabic: "يَا عَدْلُ",
        category: "names_of_allah",
      },
      {
        id: 102,
        text: "O Allah, You are Al-Latif (The Subtle). Be gentle with us in all our affairs.",
        reference: "Names of Allah",
        arabic: "يَا لَطِيفُ",
        category: "names_of_allah",
      },
      {
        id: 103,
        text: "O Allah, You are Al-Khabir (The Aware). You know our struggles; grant us relief.",
        reference: "Names of Allah",
        arabic: "يَا خَبِيرُ",
        category: "names_of_allah",
      },
      {
        id: 104,
        text: "O Allah, You are Al-Halim (The Forbearing). Be patient with us and guide us to righteousness.",
        reference: "Names of Allah",
        arabic: "يَا حَلِيمُ",
        category: "names_of_allah",
      },
      {
        id: 105,
        text: "O Allah, You are Al-Azim (The Magnificent). Fill our hearts with awe of Your magnificence.",
        reference: "Names of Allah",
        arabic: "يَا عَظِيمُ",
        category: "names_of_allah",
      },
      {
        id: 106,
        text: "O Allah, You are Al-Ghafur (The Forgiving). Forgive us for our mistakes and errors.",
        reference: "Names of Allah",
        arabic: "يَا غَفُورُ",
        category: "names_of_allah",
      },
      {
        id: 107,
        text: "O Allah, You are Ash-Shakur (The Appreciative). Accept our small deeds and multiply their reward.",
        reference: "Names of Allah",
        arabic: "يَا شَكُورُ",
        category: "names_of_allah",
      },
      {
        id: 108,
        text: "O Allah, You are Al-Ali (The Most High). Elevate our status through good deeds.",
        reference: "Names of Allah",
        arabic: "يَا عَلِيُّ",
        category: "names_of_allah",
      },
      {
        id: 109,
        text: "O Allah, You are Al-Kabir (The Great). There is nothing greater than You.",
        reference: "Names of Allah",
        arabic: "يَا كَبِيرُ",
        category: "names_of_allah",
      },
      {
        id: 110,
        text: "O Allah, You are Al-Hafiz (The Preserver). Protect us from the seen and unseen evils.",
        reference: "Names of Allah",
        arabic: "يَا حَفِيظُ",
        category: "names_of_allah",
      },
      {
        id: 111,
        text: "O Allah, You are Al-Muqit (The Sustainer). Sustain us with Your provisions.",
        reference: "Names of Allah",
        arabic: "يَا مُقِيتُ",
        category: "names_of_allah",
      },
      {
        id: 112,
        text: "O Allah, You are Al-Hasib (The Reckoner). Make our accounting easy on the Day of Judgment.",
        reference: "Names of Allah",
        arabic: "يَا حَسِيبُ",
        category: "names_of_allah",
      },
      {
        id: 113,
        text: "O Allah, You are Al-Jalil (The Majestic). Grant us a vision of Your majesty.",
        reference: "Names of Allah",
        arabic: "يَا جَلِيلُ",
        category: "names_of_allah",
      },
      {
        id: 114,
        text: "O Allah, You are Al-Karim (The Generous). Be generous with us from Your endless treasures.",
        reference: "Names of Allah",
        arabic: "يَا كَرِيمُ",
        category: "names_of_allah",
      },
      {
        id: 115,
        text: "O Allah, You are Ar-Raqib (The Watchful). Watch over us and guide us to the straight path.",
        reference: "Names of Allah",
        arabic: "يَا رَقِيبُ",
        category: "names_of_allah",
      },
      {
        id: 116,
        text: "O Allah, You are Al-Mujib (The Responsive). Respond to our prayers with what is best for us.",
        reference: "Names of Allah",
        arabic: "يَا مُجِيبُ",
        category: "names_of_allah",
      },
      {
        id: 117,
        text: "O Allah, You are Al-Wasi (The All-Encompassing). Your mercy encompasses all things.",
        reference: "Names of Allah",
        arabic: "يَا وَاسِعُ",
        category: "names_of_allah",
      },
      {
        id: 118,
        text: "O Allah, You are Al-Hakim (The Wise). Grant us wisdom in all our decisions.",
        reference: "Names of Allah",
        arabic: "يَا حَكِيمُ",
        category: "names_of_allah",
      },
    ],
};


export const quotes: Quote[] = Object.values(quotesDatabase)
  .flat()
  .map(transformQuote);


