import { type Quote } from "../types";

export const quotes: Quote[] = [
  {
    id: 1,
    text: "Indeed, with hardship comes ease.",
    source: "Qur'an",
    category: "motivation",
    reference: "94:6",
  },
  {
    id: 2,
    text: "And whoever puts their trust in Allah, then He alone is sufficient for them.",
    source: "Qur'an",
    category: "guidance",
    reference: "65:3",
  },
  {
    id: 3,
    text: "The best of people are those who are most beneficial to others.",
    source: "Hadith",
    category: "wisdom",
    reference: "Sahih al-Jami",
  },
  {
    id: 4,
    text: "Remember Me, and I will remember you.",
    source: "Qur'an",
    category: "remembrance",
    reference: "2:152",
  },
  {
    id: 5,
    text: "Our Lord, give us good in this world and good in the Hereafter.",
    source: "Qur'an",
    category: "prayer",
    reference: "2:201",
  },
  {
    id: 6,
    text: "Verily, Allah is with those who are patient.",
    source: "Qur'an",
    category: "motivation",
    reference: "2:153",
  },
  {
    id: 7,
    text: "The strong person is not the one who can overpower others, but the one who controls themselves when angry.",
    source: "Hadith",
    category: "wisdom",
    reference: "Bukhari & Muslim",
  },
  {
    id: 8,
    text: "So remember Me; I will remember you. And be grateful to Me and do not deny Me.",
    source: "Qur'an",
    category: "remembrance",
    reference: "2:152",
  },
  {
    id: 9,
    text: "Indeed, Allah does not burden a soul beyond what it can bear.",
    source: "Qur'an",
    category: "guidance",
    reference: "2:286",
  },
  {
    id: 10,
    text: "The most beloved deeds to Allah are those done consistently, even if they are small.",
    source: "Hadith",
    category: "motivation",
    reference: "Bukhari & Muslim",
  },
  {
    id: 11,
    text: "And seek help through patience and prayer.",
    source: "Qur'an",
    category: "prayer",
    reference: "2:45",
  },
  {
    id: 12,
    text: "Whoever believes in Allah and the Last Day, let them speak good or remain silent.",
    source: "Hadith",
    category: "wisdom",
    reference: "Bukhari & Muslim",
  },
  {
    id: 13,
    text: "So verily, with the hardship, there is relief. Verily, with the hardship, there is relief.",
    source: "Qur'an",
    category: "motivation",
    reference: "94:5-6",
  },
  {
    id: 14,
    text: "My Lord, expand for me my breast and ease for me my task.",
    source: "Qur'an",
    category: "prayer",
    reference: "20:25-26",
  },
  {
    id: 15,
    text: "The believer's shade on the Day of Resurrection will be their charity.",
    source: "Hadith",
    category: "guidance",
    reference: "Tirmidhi",
  },
  {
    id: 16,
    text: "When you see a person who has been given more than you, look to those who have less than you.",
    source: "Hadith",
    category: "wisdom",
    reference: "Bukhari & Muslim",
  },
  {
    id: 17,
    text: "Allah is beautiful and He loves beauty.",
    source: "Hadith",
    category: "remembrance",
    reference: "Muslim",
  },
  {
    id: 18,
    text: "Do not despair of the mercy of Allah.",
    source: "Qur'an",
    category: "motivation",
    reference: "39:53",
  },
  {
    id: 19,
    text: "My Lord, make me an establisher of prayer, and from my descendants. Our Lord, and accept my supplication.",
    source: "Qur'an",
    category: "prayer",
    reference: "14:40",
  },
  {
    id: 20,
    text: "The most complete of believers in faith are those with the best character.",
    source: "Hadith",
    category: "guidance",
    reference: "Tirmidhi",
  },
];

export const categories = [
  { id: "all", label: "All" },
  { id: "motivation", label: "Motivation" },
  { id: "prayer", label: "Prayer" },
  { id: "guidance", label: "Guidance" },
  { id: "remembrance", label: "Remembrance" },
  { id: "wisdom", label: "Wisdom" },
];
