import { type Quote } from "../types";

export const QUOTES: Quote[] = [
  {
    id: 1,
    text: "Indeed, with hardship comes ease.",
    source: "Quran",
    reference: "Quran 94:6",
    category: "motivation",
    arabic: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا",
  },
  {
    id: 2,
    text: "And He is with you wherever you are.",
    source: "Quran",
    reference: "Quran 57:4",
    category: "remembrance",
    arabic: "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ",
  },
  {
    id: 3,
    text: "The best of you are those who are best to their families.",
    source: "Hadith",
    reference: "Tirmidhi 3895",
    category: "guidance",
  },
  {
    id: 4,
    text: "Allah does not burden a soul beyond that it can bear.",
    source: "Quran",
    reference: "Quran 2:286",
    category: "motivation",
    arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
  },
  {
    id: 5,
    text: "The most beloved deeds to Allah are those done consistently, even if they are small.",
    source: "Hadith",
    reference: "Sahih Bukhari 6464",
    category: "guidance",
  },
  {
    id: 6,
    text: "When you thank Me, I give you more.",
    source: "Quran",
    reference: "Quran 14:7",
    category: "remembrance",
    arabic: "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ",
  },
  {
    id: 7,
    text: "And seek help through patience and prayer.",
    source: "Quran",
    reference: "Quran 2:45",
    category: "prayer",
    arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
  },
  {
    id: 8,
    text: "A kind word is charity.",
    source: "Hadith",
    reference: "Sahih Bukhari 6023",
    category: "wisdom",
  },
  {
    id: 9,
    text: "Verily, in the remembrance of Allah do hearts find rest.",
    source: "Quran",
    reference: "Quran 13:28",
    category: "remembrance",
    arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
  },
  {
    id: 10,
    text: "The strong person is not the one who can wrestle, but the one who controls themselves in anger.",
    source: "Hadith",
    reference: "Sahih Bukhari 6114",
    category: "wisdom",
  },
  {
    id: 11,
    text: "So remember Me; I will remember you.",
    source: "Quran",
    reference: "Quran 2:152",
    category: "remembrance",
    arabic: "فَاذْكُرُونِي أَذْكُرْكُمْ",
  },
  {
    id: 12,
    text: "Whoever relieves a believer's distress, Allah will relieve their distress on the Day of Resurrection.",
    source: "Hadith",
    reference: "Sahih Muslim 2699",
    category: "guidance",
  },
  {
    id: 13,
    text: "My mercy encompasses all things.",
    source: "Quran",
    reference: "Quran 7:156",
    category: "motivation",
    arabic: "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ",
  },
  {
    id: 14,
    text: "The best charity is that given in Ramadan.",
    source: "Hadith",
    reference: "Tirmidhi 663",
    category: "guidance",
  },
  {
    id: 15,
    text: "Your Lord has not forsaken you, nor has He become displeased.",
    source: "Quran",
    reference: "Quran 93:3",
    category: "motivation",
    arabic: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ",
  },
  {
    id: 16,
    text: "Whoever believes in Allah and the Last Day should speak good or remain silent.",
    source: "Hadith",
    reference: "Sahih Bukhari 6018",
    category: "wisdom",
  },
  {
    id: 17,
    text: "Call upon Me; I will respond to you.",
    source: "Quran",
    reference: "Quran 40:60",
    category: "prayer",
    arabic: "ادْعُونِي أَسْتَجِبْ لَكُمْ",
  },
  {
    id: 18,
    text: "The believer's shade on the Day of Resurrection will be their charity.",
    source: "Hadith",
    reference: "Tirmidhi 604",
    category: "guidance",
  },
  {
    id: 19,
    text: "Do not lose hope, nor be sad.",
    source: "Quran",
    reference: "Quran 3:139",
    category: "motivation",
    arabic: "وَلَا تَهِنُوا وَلَا تَحْزَنُوا",
  },
  {
    id: 20,
    text: "The best of people are those who are most beneficial to others.",
    source: "Hadith",
    reference: "Al-Mu'jam al-Awsat 5787",
    category: "wisdom",
  },
];
